//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CTHDB
    {
        public string mahdb { get; set; }
        public string masp { get; set; }
        public Nullable<double> soluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
    
        public virtual tb_HDB tb_HDB { get; set; }
        public virtual tb_Sanpham tb_Sanpham { get; set; }
    }
}
