//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Sanpham()
        {
            this.tb_CTHDB = new HashSet<tb_CTHDB>();
        }
    
        public string masp { get; set; }
        public string tensp { get; set; }
        public string maloai { get; set; }
        public Nullable<double> gianhap { get; set; }
        public Nullable<double> giaban { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public byte[] hinhanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDB> tb_CTHDB { get; set; }
        public virtual tb_Loai tb_Loai { get; set; }
    }
}
