//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AllSanPham
    {
        public string masp { get; set; }
        public string tensp { get; set; }
        public string tenloai { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> gianhap { get; set; }
        public Nullable<double> giaban { get; set; }
        public byte[] hinhanh { get; set; }
    }
}
