//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_InHoaDon
    {
        public string mahdb { get; set; }
        public Nullable<System.DateTime> ngayban { get; set; }
        public string manv { get; set; }
        public string tennv { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string masp { get; set; }
        public string tensp { get; set; }
        public string tenloai { get; set; }
        public Nullable<double> soluong { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public Nullable<double> tongtien { get; set; }
    }
}
