//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsReport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_QuancapheEntities : DbContext
    {
        public QL_QuancapheEntities()
            : base("name=QL_QuancapheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_CTHDB> tb_CTHDB { get; set; }
        public virtual DbSet<tb_CTHDN> tb_CTHDN { get; set; }
        public virtual DbSet<tb_HDB> tb_HDB { get; set; }
        public virtual DbSet<tb_HDN> tb_HDN { get; set; }
        public virtual DbSet<tb_Khachhang> tb_Khachhang { get; set; }
        public virtual DbSet<tb_Loai> tb_Loai { get; set; }
        public virtual DbSet<tb_NCC> tb_NCC { get; set; }
        public virtual DbSet<tb_Nhanvien> tb_Nhanvien { get; set; }
        public virtual DbSet<tb_Sanpham> tb_Sanpham { get; set; }
        public virtual DbSet<tb_User> tb_User { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<View_CTHDB> View_CTHDB { get; set; }
        public virtual DbSet<View_CTHDN> View_CTHDN { get; set; }
        public virtual DbSet<View_KhachHang> View_KhachHang { get; set; }
        public virtual DbSet<View_NhanVien> View_NhanVien { get; set; }
        public virtual DbSet<View_SanPham> View_SanPham { get; set; }
    }
}
