//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NCC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NCC()
        {
            this.tb_CTHDN = new HashSet<tb_CTHDN>();
        }
    
        public string mancc { get; set; }
        public string tenncc { get; set; }
        public string diachi { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public string sdt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CTHDN> tb_CTHDN { get; set; }
    }
}
