//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductsReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CTHDN
    {
        public string mahdn { get; set; }
        public string tensp { get; set; }
        public string tenncc { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<double> thanhtien { get; set; }
        public Nullable<double> tongtien { get; set; }
    }
}
